language: python

install:
  - pip install pylint

script:
  - mkdir -p reports/pylint
  - pylint --rcfile=.pylintrc src/*/*.py > reports/pylint/pylint_report.txt || exit 0
  - cat reports/pylint/pylint_report.txt
