language: python
python:
  - "3.6"

install:
  - pip install pylint
  - pip install pytest
  - pip install pytest-cov
  - pip install behave
  - pip install xenon

stages:
  - build
  - static analysis
  - unit test

jobs:
  include:
    - stage: build
      script: echo "building..."
    - stage: static analysis
      script: pylint --rcfile=.pylintrc src/*/*.py
      script: xenon -a A -b B -m A src/misra
      script: radon cc -s src/misra
    - stage: unit test
      script: pytest --cov=src/misra --cov-branch
