language: python
python:
  - "3.6"
  
install:
  - pip install pylint
  - pip install pytest
  - pip install pytest-cov
  - pip install behave

script:
  - pylint --rcfile=.pylintrc src/*/*.py
  - pytest --cov=src/misra --cov-branch
