""" Parses violations found by the tool understand into a standardized structure."""
import re


def parse_understand_violations(violations, guidelines):
    """Parse the violations generated by the tool understand."""

    guideline_violations = []

    for violation in violations:
        file, violation, line, column, check, entity = violation

        result = re.search(r'^([0-9]+\.[0-9]+)', check)
        if result:
            rule = result.group(1)
            if rule in guidelines.keys():
                guideline_violation = (guidelines[rule], file, line, column, entity)
                guideline_violations.append(guideline_violation)
            else:
                print("rule not found in guidelines")
        else:
            print("could not determine rule in violation")

    return guideline_violations
